version: "3"

services:

  manual:
    build: server
    volumes:
    - ${DOC_SOURCE}:/opt/sphinx/doc/:ro
    - ${DOC_OUTPUT}:/usr/share/nginx/html
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
    - ${HTTP_PORT}:80